#!/usr/bin/sh

BLOG=blog
TEMPLATES=templates
SOURCE=sauce
LIST_DIR=$TEMPLATES/list_of_all.html
LIST_TAGS=$TEMPLATES/list_of_tags.html

makeit(){
    posts=$(ls $BLOG/$SOURCE/*md 2>/dev/null)

    [ ! -z "$posts" ] && \
        for post in $posts
        do
            data=$(grep date $post | sed 's/date.*\s//g')
            pandoc --template $TEMPLATES/template_blog.html -f gfm $post -o $(echo ${post%%.md}.html | sed "s/sauce\//post\/$data/g")
            echo $post
        done
}

postit(){
    posts=$(ls $BLOG/post | sort -nfr)

    > $LIST_DIR 

    [ ! -z "$posts" ] && \
        for post in $posts
        do
            title=$(grep "title" $BLOG/post/$post | cut -d '<' -f2 | sed 's/^title.*>//g')
            printf "\t\t\t$(printf "$post" | sed 's/^/<a class="post_link" href="post\//' | sed "s/$/\">$title<\/a><br>/")\n" >> $LIST_DIR
        done

}

tags(){
    tag_html=$(grep -hA10 tags $BLOG/$SOURCE/* 2>/dev/null | grep -P "^\s+\-.*" | sed "s/^\s\+\-\s//g; s/$/.html/g" | sort | uniq -i)
    tag_list=$(echo "$tag_html" | sed "s/^/$BLOG\/tags\//g")

    rm $BLOG/tags/*

    [ ! -z "$tag_list" ] && \
        for tag in $tag_list; do
            cp $TEMPLATES/template_tags.html $tag 2>/dev/null
            t=${tag%.html}
            t=${tag#$BLOG/tags/}
            posts=$(grep -iH "tags.*$t" $BLOG/post/* 2>/dev/null | cut -d: -f1)
            title=$(echo $tag | sed "s/\.html//g; s/$BLOG\/tags\///g")
            printf "\t<h1>marcados como: $title</h1>\n\t<hr>\n" >> $tag
            for post in $posts; do
                post_title=$(grep title $post | sed 's/<title>//; s/<\/title>//')
                printf "\t\t$(echo "$post" | sed "s/blog/\.\./; s/^/<a class="post_link" href=\"/; s/$/\">$post_title<\/a><br>/")\n" >> $tag
            done
            printf "\t</div>\n\t<body>\n</html>" >> $tag
        done

    > $LIST_TAGS

    printf "\t\t<center><h1>Tags</h1></center><hr>\n" >> $LIST_TAGS
    printf "\t\t<ul class="tags">\n" >> $LIST_TAGS

    for tag in $tag_html; do
        echo "\t\t\t<li><a href="tags/$tag">${tag%.html}<a/></li>" >> $LIST_TAGS
    done

    printf "\t\t</ul>\n" >> $LIST_TAGS

    cat $LIST_TAGS >> $LIST_DIR

    printf "\t</div>\n\t</body>\n</html>" >> $LIST_DIR

    export LIST_OF_POSTS=$(cat $LIST_DIR)

    cat $TEMPLATES/template_index.html | envsubst > $BLOG/index.html

}

makeit
postit
tags

echo "\033[045mDONE! 😎\033[0m"
