#!/usr/bin/sh

read -rp "Insert a name for the new file: " name
BLOG=blog
SOURCE=sauce
post=$BLOG/$SOURCE/$(echo $name | tr ' ' '-').md

if [ -f $post ]; then
    echo "$post \033[041mAlready exists\033[0m!!!"
else
    echo "---\ntitle: \ndate: $(date +%F)\ntags:\n  -\n---" > $post

    touch $post
    
    $EDITOR $post
fi
