#!/usr/bin/sh
dir=./blog/sauce
pdir=./blog/post

list_n(){
    ls $dir | nl
}

grep_html(){
    ls $pdir | grep $1.html
}

list_n

read -p "select the post number you wanna delete: " post

pick="$(list_n | grep -w $post | awk '{print $2}')"

if [ ! -z $pick ]; then
    read -p 'are you sure? ' sure && echo $sure | grep -iP "y|s" && rm $dir/$pick && rm $pdir/$(grep_html ${pick%%.*})
else
    echo "not an option"
fi
